select distinct JOB_ID from EMPLOYEES;

select avg(SALARY) from EMPLOYEES
where JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) , count(*), sum(SALARY), min(SALARY), max(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;


--> dISPLAY HOW MANY DEPARTMENTS WE HAVE IN EACH LOCATION
SELECT LOCATION_ID,  COUNT(DEPARTMENT_NAME)
FROM DEPARTMENTS
GROUP BY LOCATION_ID ;

SELECT LOCATION_ID,  COUNT(DEPARTMENT_NAME)
FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY COUNT(*) desc;

SELECT LOCATION_ID,  COUNT(DEPARTMENT_NAME)
FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY 2 asc;

--> Display how many countries we have in each regions
SELECT REGION_ID, COUNT(COUNTRY_NAME)
FROM COUNTRIES
GROUP BY REGION_ID
order by count(*) asc;

select * from EMPLOYEES;

select DEPARTMENT_ID, sum(SALARY), COUNT(*)
from EMPLOYEES
group by DEPARTMENT_ID;

select DEPARTMENT_ID, sum(SALARY), COUNT(*)
from EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
group by DEPARTMENT_ID;


SELECT JOB_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) > 5000;

select DEPARTMENT_ID, ROUND(AVG(SALARY))
from EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
group by DEPARTMENT_ID
having AVG(SALARY) > 6000
ORDER BY 2;

SELECT FIRST_NAME, COUNT(*)
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*) > 1;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 5
order by 2 desc;