select * from EMPLOYEES;

select * from EMPLOYEES
where FIRST_NAME = 'David';

select * from EMPLOYEES
where FIRST_NAME = 'David' and LAST_NAME = 'Lee';

select FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES
where FIRST_NAME = 'Peter';

select * from EMPLOYEES
         where SALARY >6000;

select EMAIL
from EMPLOYEES
where SALARY < 5000;

select * from EMPLOYEES
where SALARY > 7000
and DEPARTMENT_ID = 60;

select * from EMPLOYEES
where SALARY >= 3000 and SALARY <= 7000;

select * from EMPLOYEES
where SALARY between 3000 and 7000;

select * from EMPLOYEES
where JOB_ID = 'IT_PROG' OR JOB_ID = 'MK_MAN';

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 121 ;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (121, 142, 154, 165, 187);

SELECT * FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG', 'MK_MAN');

SELECT * FROM COUNTRIES
WHERE COUNTRY_ID IN ('US', 'IT');

SELECT * FROM COUNTRIES
WHERE COUNTRY_ID NOT IN ('US', 'IT');

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM EMPLOYEES
WHERE MANAGER_ID IS NULL ;




