select * from CUSTOMER;

select * from ADDRESS;

select FIRST_NAME, LAST_NAME, ADDRESS, PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID=ADDRESS.ADDRESS_ID;
SELECT * FROM CUSTOMER;

select FIRST_NAME, LAST_NAME,ADDRESS.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID=ADDRESS.ADDRESS_ID;

select FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C join ADDRESS A
 on C.ADDRESS_ID=A.ADDRESS_ID;

select FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C INNER JOIN ADDRESS A
                     on C.ADDRESS_ID=A.ADDRESS_ID;

--> Left Outer Join
select FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C lEFT OUTER JOIN ADDRESS A
                           on C.ADDRESS_ID=A.ADDRESS_ID;

--> Right Outer Join/ Right Join
select FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C Right OUTER JOIN ADDRESS A
                                on C.ADDRESS_ID=A.ADDRESS_ID;

--> Full Outer Join/ Full Join
select FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C FUll OUTER JOIN ADDRESS A
                                 on C.ADDRESS_ID=A.ADDRESS_ID;










