select * from EMPLOYEES;

select FIRST_NAME, E.DEPARTMENT_ID , DEPARTMENT_NAME
from EMPLOYEES E join DEPARTMENTS D
on E.DEPARTMENT_ID=D.DEPARTMENT_ID;

select FIRST_NAME, E.DEPARTMENT_ID , DEPARTMENT_NAME
from EMPLOYEES E join DEPARTMENTS D
on E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY FIRST_NAME asc;

select FIRST_NAME, E.DEPARTMENT_ID , DEPARTMENT_NAME
from EMPLOYEES E left join DEPARTMENTS D
                      on E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY FIRST_NAME asc;

select FIRST_NAME, E.DEPARTMENT_ID , DEPARTMENT_NAME
from DEPARTMENTS D right join EMPLOYEES E
                           on D.DEPARTMENT_ID=E.DEPARTMENT_ID
ORDER BY FIRST_NAME asc;

select FIRST_NAME, E.DEPARTMENT_ID , DEPARTMENT_NAME
from EMPLOYEES E RIGHT join DEPARTMENTS D
                           on E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY FIRST_NAME asc;

--> hOW MANY EMPLOYEE WE HAVE FOR EACH DEPARTMENT NAME?
select DEPARTMENT_NAME, COUNT(*)
from EMPLOYEES E join DEPARTMENTS D
                            on E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E FULL JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;

SELECT  COUNTRY_NAME, CITY
FROM LOCATIONS L JOIN COUNTRIES C
ON L.COUNTRY_ID=C.COUNTRY_ID;

SELECT  COUNTRY_NAME, CITY
FROM LOCATIONS L RIGHT JOIN COUNTRIES C
 ON L.COUNTRY_ID=C.COUNTRY_ID;

SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

SELECT DEPARTMENT_NAME, STREET_ADDRESS
FROM DEPARTMENTS D JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID;

SELECT DEPARTMENT_NAME, STREET_ADDRESS
FROM DEPARTMENTS D lEFT JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID;

SELECT DEPARTMENT_NAME, STREET_ADDRESS
FROM DEPARTMENTS D RIGHT JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

--> 3 TABLE CONNECTION
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
    ON D.LOCATION_ID=L.LOCATION_ID;

--> 4 TABLE CONNECTIONS
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
                      ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                 JOIN LOCATIONS L
                      ON D.LOCATION_ID=L.LOCATION_ID
                 JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

--> 5 TABLE CONNECTIONS
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
                      ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                 JOIN LOCATIONS L
                      ON D.LOCATION_ID=L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN REGIONS R ON C.REGION_ID=R.REGION_ID;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;

SELECT COUNTRY_NAME, COUNT(FIRST_NAME)
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
group by COUNTRY_NAME
HAVING COUNT(*) > 10;

--> LEFT JOIN WITH WHERE CLAUSE
SELECT *
FROM CUSTOMER C LEFT JOIN ADDRESS A
ON A.ADDRESS_ID = C.ADDRESS_ID
WHERE A.ADDRESS_ID IS NULL ;

--> FULL JOIN WITH WHERE CLAUSE
SELECT *
FROM CUSTOMER C FULL JOIN ADDRESS A
                          ON A.ADDRESS_ID = C.ADDRESS_ID
WHERE A.ADDRESS_ID IS NULL OR C.CUSTOMER_ID IS NULL ;




